"""initial schema

Revision ID: 362f8cc3cf8a
Revises: 
Create Date: 2026-08-12 13:44:29.024708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362f8cc3cf8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('base_weight', sa.Float(), nullable=False),
    sa.Column('minimum_confidence', sa.Float(), nullable=False),
    sa.Column('israel_relevance_required', sa.Boolean(), nullable=False),
    sa.Column('directness', sa.String(length=50), nullable=False),
    sa.Column('conditions_json', sa.Text(), nullable=True),
    sa.Column('positive_indicators_json', sa.Text(), nullable=True),
    sa.Column('negative_indicators_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_articles', sa.Integer(), nullable=False),
    sa.Column('global_articles', sa.Integer(), nullable=False),
    sa.Column('israel_articles', sa.Integer(), nullable=False),
    sa.Column('dominant_stage', sa.String(length=50), nullable=True),
    sa.Column('secondary_stage', sa.String(length=50), nullable=True),
    sa.Column('dominant_event_types_json', sa.Text(), nullable=True),
    sa.Column('stage_distribution_json', sa.Text(), nullable=True),
    sa.Column('global_pattern', sa.Text(), nullable=True),
    sa.Column('israel_pattern', sa.Text(), nullable=True),
    sa.Column('father_pattern', sa.Text(), nullable=True),
    sa.Column('mother_pattern', sa.Text(), nullable=True),
    sa.Column('son_perspective', sa.Text(), nullable=True),
    sa.Column('relationship_pattern', sa.Text(), nullable=True),
    sa.Column('future_pattern', sa.Text(), nullable=True),
    sa.Column('trend_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('telegram_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_date')
    )
    op.create_table('news_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('developmental_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('developmental_stage', sa.String(length=50), nullable=False),
    sa.Column('stage_score', sa.Integer(), nullable=False),
    sa.Column('mother_analogy_score', sa.Integer(), nullable=False),
    sa.Column('mother_analogy_text', sa.Text(), nullable=True),
    sa.Column('father_analogy_score', sa.Integer(), nullable=False),
    sa.Column('father_analogy_text', sa.Text(), nullable=True),
    sa.Column('son_perspective_json', sa.Text(), nullable=True),
    sa.Column('scientific_context_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('event_classifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('secondary_event_types', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('israel_relevance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('relevance_type', sa.String(length=50), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('entities_json', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('israel_relevance')
    op.drop_table('event_classifications')
    op.drop_table('developmental_analyses')
    op.drop_table('news_articles')
    op.drop_table('telegram_messages')
    op.drop_table('system_logs')
    op.drop_table('news_sources')
    op.drop_table('daily_summaries')
    op.drop_table('classification_rules')
    # ### end Alembic commands ###
